import React, { useState, useEffect } from "react";
import { 
  FiFileText, 
  FiDownload, 
  FiAlertTriangle, 
  FiBookOpen,
  FiActivity
} from "react-icons/fi";
import apiService from "../services/api";
import type { ReportItem } from "../types";

export const Reports: React.FC = () => {
  const [reportsList, setReportsList] = useState<ReportItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState<string | null>(null);

  // Fetch report items on mount
  useEffect(() => {
    const fetchReports = async () => {
      try {
        setError(null);
        const data = await apiService.getReports();
        
        // Let's check if dataset_report.md is also present on disk, 
        // since the backend scans reports/ folder but only maps specified template names.
        // We can manually add dataset_report.md to the list if we know it exists,
        // but the backend list is already dynamic and safe.
        // To be safe and comprehensive, let's display what the backend returns.
        setReportsList(data);
      } catch (err) {
        setError("Could not discover generated reports on the backend server.");
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const handleDownload = async (filename: string) => {
    setDownloading(filename);
    setError(null);
    try {
      await apiService.downloadReport(filename);
    } catch (err) {
      setError(`Download failed for ${filename}. Confirm the backend is online and the report exists.`);
    } finally {
      setDownloading(null);
    }
  };

  // Helper mapping icon types
  const getIcon = (type: string) => {
    switch (type) {
      case "markdown":
        return <FiBookOpen className="text-xl text-accent-cyan" />;
      case "csv":
        return <FiActivity className="text-xl text-accent-emerald" />;
      default:
        return <FiFileText className="text-xl text-accent-blue" />;
    }
  };

  return (
    <div className="flex-1 bg-background p-8 space-y-8 overflow-y-auto max-h-[calc(100vh-64px)] font-sans">
      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white m-0">
          Inspection Performance Reports
        </h1>
        <p className="text-xs text-gray-400 font-medium">
          Download evaluation matrices, training logs, and comparison documents generated by the machine learning pipeline.
        </p>
      </div>

      {/* Sync Alerts */}
      {error && (
        <div className="bg-accent-red/10 border border-accent-red/30 rounded-lg p-3 flex items-start space-x-3 text-accent-red text-xs">
          <FiAlertTriangle className="shrink-0 text-sm mt-0.5" />
          <span>{error}</span>
        </div>
      )}

      {/* Main Grid View */}
      {loading ? (
        <div className="py-20 text-center text-gray-400">
          <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-accent-blue mx-auto mb-4"></div>
          <p className="text-xs font-semibold tracking-wide uppercase">Scanning server storage folders...</p>
        </div>
      ) : reportsList.length === 0 ? (
        <div className="glass-panel p-12 text-center text-gray-500 space-y-3">
          <FiFileText className="text-4xl text-gray-700 mx-auto" />
          <p className="text-sm font-semibold">No performance report files discovered</p>
          <p className="text-xs text-gray-600 max-w-sm mx-auto leading-relaxed">
            Run the model training or evaluation pipelines on the backend system to write classification summaries and metrics to disk.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {reportsList.map((report) => (
            <div
              key={report.filename}
              className="glass-panel p-5 flex items-start justify-between border border-gray-800/80 hover:border-gray-700 transition-colors duration-200"
            >
              <div className="flex space-x-4 items-start">
                <div className="h-10 w-10 rounded-lg bg-gray-900 border border-gray-800 flex items-center justify-center">
                  {getIcon(report.type)}
                </div>
                <div className="space-y-1">
                  <h3 className="text-sm font-bold text-white leading-tight m-0">
                    {report.name}
                  </h3>
                  <p className="text-[10px] text-gray-500 font-mono">
                    {report.filename}
                  </p>
                  <span className="inline-block text-[9px] uppercase font-bold tracking-widest text-accent-cyan bg-accent-cyan/10 border border-accent-cyan/20 px-1.5 py-0.5 rounded mt-1.5">
                    {report.type}
                  </span>
                </div>
              </div>

              <button
                onClick={() => handleDownload(report.filename)}
                disabled={downloading !== null}
                className="bg-gray-800 hover:bg-accent-blue/20 hover:text-accent-blue text-gray-300 p-2.5 rounded-lg border border-gray-700 hover:border-accent-blue/30 transition-all duration-200"
                title={`Download ${report.filename}`}
              >
                {downloading === report.filename ? (
                  <div className="animate-spin rounded-full h-4 w-4 border-t-2 border-b-2 border-white"></div>
                ) : (
                  <FiDownload className="text-sm" />
                )}
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Guide details */}
      <div className="glass-panel p-6 space-y-3">
        <span className="text-xs font-bold text-gray-500 uppercase tracking-widest block border-b border-gray-800 pb-2">
          Diagnostic Document Guide
        </span>
        <p className="text-xs text-gray-400 leading-relaxed">
          The reports listed above represent official model diagnostics generated in the local server folder path under the <code className="bg-gray-950 px-1 rounded border border-gray-800 font-mono text-[10px] text-accent-cyan">reports/</code> directory. For customized comparisons or raw dataset splits allocations, please trigger training evaluator scripts directly in your system console.
        </p>
      </div>
    </div>
  );
};
export default Reports;
